version: '3'
services:
  node-app:
    build:
      context: ./
      args:
        - NODE_ENV=development
    environment:
      - SALT_PASSWORD=36ab95b45774dc9465fe09a30e80f397
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:password@mysqldb:3306/k8s_dev?connect_timeout=3000
    ports:
      - 8080:80
    volumes:
      - ./:/app:ro
      - /app/node_modules
  mysqldb:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=k8s_dev
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume:

networks:
  backend: