version: '3'
services:
  node-app:
    depends_on:
      - mysql
    build:
      context: ./
      args:
        - NODE_ENV=development
    environment:
      - HTTP_PORT=80
      - SALT_PASSWORD=36ab95b45774dc9465fe09a30e80f397
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:password@mysqlnode:3306/k8s_dev?connect_timeout=200
    ports:
      - 8080:80
    networks:
      - backend
    volumes:
      - ./:/app:ro
      - /app/node_modules
  mysqlnode:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=k8s_dev
    networks:
      - backend
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume:

networks:
  backend: