version: '3'
services:
  node-app:
    # error node-app could not connect to database
    # depends_on:
    #   - mysqldb
    environment:
      - HTTP_PORT=80
    networks:
      - backend
  mysqldb:
    image: mysql
    networks:
      - backend

networks:
  backend: